"""PostgreSQL booking foundation models.

The range columns are generated by PostgreSQL and are used by GiST exclusion
constraints.  Application checks improve error messages, while the database remains
the authority under concurrent writes.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, time
from typing import Any

from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Time,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSTZRANGE, UUID, ExcludeConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def uuid_default() -> uuid.UUID:
    return uuid.uuid4()


class Base(DeclarativeBase):
    """Declarative metadata root."""


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )


class Actor(Base, TimestampMixin):
    __tablename__ = "actors"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    subject_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))

    patient_profile: Mapped[PatientProfile | None] = relationship(back_populates="actor")
    doctor_profile: Mapped[Doctor | None] = relationship(back_populates="actor")

    __table_args__ = (
        CheckConstraint("role IN ('patient', 'doctor', 'admin')", name="ck_actors_role"),
    )


class PatientProfile(Base, TimestampMixin):
    __tablename__ = "patient_profiles"

    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="RESTRICT"), primary_key=True
    )
    display_name: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'Patient'")
    )
    timezone: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'UTC'"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    actor: Mapped[Actor] = relationship(back_populates="patient_profile")
    holds: Mapped[list[SlotHold]] = relationship(back_populates="patient")
    appointments: Mapped[list[Appointment]] = relationship(back_populates="patient")

    __table_args__ = (CheckConstraint("version > 0", name="ck_patient_profiles_version"),)


class Doctor(Base, TimestampMixin):
    __tablename__ = "doctors"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("actors.id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
    )
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    credentials: Mapped[str | None] = mapped_column(Text)
    specialization: Mapped[str | None] = mapped_column(Text)
    timezone: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'UTC'"))
    appointment_durations_minutes: Mapped[list[int]] = mapped_column(
        ARRAY(Integer), nullable=False, server_default=text("ARRAY[30]::integer[]")
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    schedule_version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    actor: Mapped[Actor] = relationship(back_populates="doctor_profile")
    working_hours: Mapped[list[DoctorWorkingHour]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan"
    )
    leave: Mapped[list[DoctorLeave]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan"
    )
    holds: Mapped[list[SlotHold]] = relationship(back_populates="doctor")
    appointments: Mapped[list[Appointment]] = relationship(back_populates="doctor")

    __table_args__ = (
        CheckConstraint("version > 0", name="ck_doctors_version"),
        CheckConstraint("schedule_version > 0", name="ck_doctors_schedule_version"),
    )


class DoctorWorkingHour(Base, TimestampMixin):
    __tablename__ = "doctor_working_hours"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False
    )
    weekday: Mapped[int] = mapped_column(Integer, nullable=False)
    starts_local: Mapped[time] = mapped_column(Time, nullable=False)
    ends_local: Mapped[time] = mapped_column(Time, nullable=False)

    doctor: Mapped[Doctor] = relationship(back_populates="working_hours")

    __table_args__ = (
        CheckConstraint("weekday BETWEEN 0 AND 6", name="ck_working_hours_weekday"),
        CheckConstraint("starts_local < ends_local", name="ck_working_hours_interval"),
        UniqueConstraint(
            "doctor_id", "weekday", "starts_local", "ends_local", name="uq_working_hours_interval"
        ),
        Index("ix_working_hours_doctor_weekday", "doctor_id", "weekday"),
    )


class DoctorLeave(Base, TimestampMixin):
    __tablename__ = "doctor_leave"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reason: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    doctor: Mapped[Doctor] = relationship(back_populates="leave")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_doctor_leave_interval"),
        CheckConstraint("version > 0", name="ck_doctor_leave_version"),
        Index("ix_doctor_leave_doctor_interval", "doctor_id", "starts_at", "ends_at"),
    )


class SlotHold(Base, TimestampMixin):
    __tablename__ = "slot_holds"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.actor_id", ondelete="RESTRICT"),
        nullable=False,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    slot_range: Mapped[Any] = mapped_column(
        TSTZRANGE,
        Computed("tstzrange(starts_at, ends_at, '[)'::text)", persisted=True),
        nullable=False,
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'active'"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    patient: Mapped[PatientProfile] = relationship(back_populates="holds")
    doctor: Mapped[Doctor] = relationship(back_populates="holds")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_slot_holds_interval"),
        CheckConstraint(
            "status IN ('active', 'released', 'expired', 'converted')", name="ck_slot_holds_status"
        ),
        ExcludeConstraint(
            ("doctor_id", "="),
            ("slot_range", "&&"),
            where=text("status = 'active'"),
            name="ex_slot_holds_active_overlap",
        ),
        Index("ix_slot_holds_patient_status", "patient_id", "status"),
        Index("ix_slot_holds_doctor_status_expiry", "doctor_id", "status", "expires_at"),
    )


class Appointment(Base, TimestampMixin):
    __tablename__ = "appointments"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.actor_id", ondelete="RESTRICT"),
        nullable=False,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    slot_range: Mapped[Any] = mapped_column(
        TSTZRANGE,
        Computed("tstzrange(starts_at, ends_at, '[)'::text)", persisted=True),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'confirmed'"))
    symptoms_text: Mapped[str] = mapped_column(Text, nullable=False)
    urgency: Mapped[str | None] = mapped_column(Text)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    patient: Mapped[PatientProfile] = relationship(back_populates="appointments")
    doctor: Mapped[Doctor] = relationship(back_populates="appointments")
    outbox_events: Mapped[list[OutboxEvent]] = relationship(back_populates="appointment")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_appointments_interval"),
        CheckConstraint(
            "status IN ("
            "'confirmed', 'in_progress', 'completed', "
            "'cancelled_patient', 'cancelled_doctor', "
            "'cancelled_admin', 'cancelled_doctor_leave'"
            ")",
            name="ck_appointments_status",
        ),
        CheckConstraint(
            "urgency IS NULL OR urgency IN ('routine', 'soon', 'urgent')",
            name="ck_appointments_urgency",
        ),
        ExcludeConstraint(
            ("doctor_id", "="),
            ("slot_range", "&&"),
            where=text("status IN ('confirmed', 'in_progress')"),
            name="ex_appointments_active_overlap",
        ),
        Index("ix_appointments_patient_starts", "patient_id", "starts_at"),
        Index("ix_appointments_doctor_starts", "doctor_id", "starts_at"),
        Index("ix_appointments_status_starts", "status", "starts_at"),
    )


class IdempotencyRecord(Base):
    __tablename__ = "idempotency_records"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="RESTRICT"), nullable=False
    )
    method: Mapped[str] = mapped_column(String(8), nullable=False)
    route_template: Mapped[str] = mapped_column(Text, nullable=False)
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False)
    request_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    status_code: Mapped[int | None] = mapped_column(Integer)
    response_body: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint(
            "actor_id", "method", "route_template", "idempotency_key", name="uq_idempotency_scope"
        ),
        Index("ix_idempotency_created_at", "created_at"),
    )


class OutboxEvent(Base):
    __tablename__ = "outbox_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    aggregate_type: Mapped[str] = mapped_column(Text, nullable=False)
    aggregate_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE")
    )
    dedupe_key: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    correlation_id: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'system'")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    next_attempt_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    last_error_code: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    appointment: Mapped[Appointment | None] = relationship(back_populates="outbox_events")

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'processing', 'succeeded', 'retrying', 'failed')",
            name="ck_outbox_status",
        ),
        CheckConstraint("version > 0", name="ck_outbox_version"),
        UniqueConstraint(
            "event_type", "aggregate_type", "aggregate_id", "dedupe_key", name="uq_outbox_dedupe"
        ),
        Index("ix_outbox_appointment_id", "appointment_id"),
        Index("ix_outbox_claimable", "status", "next_attempt_at"),
    )


class AuditEvent(Base):
    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    action: Mapped[str] = mapped_column(Text, nullable=False)
    resource_type: Mapped[str] = mapped_column(Text, nullable=False)
    resource_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    request_id: Mapped[str | None] = mapped_column(Text)
    outcome: Mapped[str] = mapped_column(Text, nullable=False)
    reason: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("ix_audit_events_resource", "resource_type", "resource_id", "created_at"),
        Index("ix_audit_events_actor_created", "actor_id", "created_at"),
    )


class SymptomVersion(Base):
    """Immutable patient symptom source records."""

    __tablename__ = "symptom_versions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    symptoms_text: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'patient'"))
    created_by_actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint("version > 0", name="ck_symptom_versions_version"),
        CheckConstraint("source IN ('patient', 'imported')", name="ck_symptom_versions_source"),
        UniqueConstraint("appointment_id", "version", name="uq_symptom_versions_appointment"),
        Index("ix_symptom_versions_appointment", "appointment_id", "version"),
    )


class Visit(Base, TimestampMixin):
    """One doctor workspace and immutable completion boundary per appointment."""

    __tablename__ = "visits"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="RESTRICT"), nullable=False
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'draft'"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    urgency: Mapped[str | None] = mapped_column(Text)
    follow_up_instructions: Mapped[str | None] = mapped_column(Text)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("appointment_id", name="uq_visits_appointment"),
        CheckConstraint("status IN ('draft', 'completed')", name="ck_visits_status"),
        CheckConstraint("version > 0", name="ck_visits_version"),
        CheckConstraint(
            "urgency IS NULL OR urgency IN ('routine', 'soon', 'urgent')",
            name="ck_visits_urgency",
        ),
        CheckConstraint(
            "follow_up_instructions IS NULL OR char_length(follow_up_instructions) <= 10000",
            name="ck_visits_follow_up_instructions_length",
        ),
        Index("ix_visits_doctor_status", "doctor_id", "status"),
    )


class VisitNoteVersion(Base):
    """Append-only doctor-authored note versions."""

    __tablename__ = "visit_note_versions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    visit_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visits.id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    notes_text: Mapped[str] = mapped_column(Text, nullable=False)
    author_actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint("version > 0", name="ck_visit_note_versions_version"),
        UniqueConstraint("visit_id", "version", name="uq_visit_note_versions_visit"),
        Index("ix_visit_note_versions_visit", "visit_id", "version"),
    )


class Prescription(Base, TimestampMixin):
    """Structured prescription envelope; prose is advisory and never parsed."""

    __tablename__ = "prescriptions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    visit_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visits.id", ondelete="RESTRICT"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'draft'"))
    advisory_text: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        UniqueConstraint("visit_id", name="uq_prescriptions_visit"),
        CheckConstraint("version > 0", name="ck_prescriptions_version"),
        CheckConstraint("status IN ('draft', 'completed')", name="ck_prescriptions_status"),
    )


class PrescriptionItem(Base):
    """Deterministic medication schedule source fields."""

    __tablename__ = "prescription_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    prescription_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("prescriptions.id", ondelete="CASCADE"), nullable=False
    )
    medication_name: Mapped[str] = mapped_column(Text, nullable=False)
    dosage: Mapped[str] = mapped_column(Text, nullable=False)
    route: Mapped[str | None] = mapped_column(Text)
    frequency: Mapped[str] = mapped_column(Text, nullable=False)
    start_date: Mapped[date] = mapped_column(nullable=False)
    end_date: Mapped[date | None] = mapped_column()
    duration_days: Mapped[int | None] = mapped_column(Integer)
    instructions: Mapped[str] = mapped_column(Text, nullable=False)
    prescriber_actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "frequency IN ("
            "'once_daily', 'twice_daily', 'three_times_daily', 'every_4_hours', 'as_needed'"
            ")",
            name="ck_prescription_items_frequency",
        ),
        CheckConstraint(
            "duration_days IS NULL OR duration_days BETWEEN 1 AND 3650",
            name="ck_prescription_items_duration",
        ),
        CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name="ck_prescription_items_dates"
        ),
        Index("ix_prescription_items_prescription", "prescription_id"),
    )


class GeneratedArtifact(Base, TimestampMixin):
    """Versioned, visibly advisory generated output."""

    __tablename__ = "generated_artifacts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE")
    )
    visit_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visits.id", ondelete="CASCADE")
    )
    artifact_type: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    content: Mapped[str | None] = mapped_column(Text)
    source_record_type: Mapped[str] = mapped_column(Text, nullable=False)
    source_record_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    source_versions: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    task_version: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'v1'"))
    provider: Mapped[str | None] = mapped_column(Text)
    model: Mapped[str | None] = mapped_column(Text)
    error_code: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        CheckConstraint(
            "artifact_type IN ('pre_visit_brief', 'post_visit_summary')",
            name="ck_generated_artifacts_type",
        ),
        CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed')", name="ck_generated_artifacts_status"
        ),
        CheckConstraint(
            "appointment_id IS NOT NULL OR visit_id IS NOT NULL",
            name="ck_generated_artifacts_owner",
        ),
        Index("ix_generated_artifacts_appointment", "appointment_id", "artifact_type"),
        Index("ix_generated_artifacts_visit", "visit_id", "artifact_type"),
    )


class ReminderPreference(Base, TimestampMixin):
    __tablename__ = "reminder_preferences"

    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.actor_id", ondelete="CASCADE"),
        primary_key=True,
    )
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    channel: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'email'"))
    timezone: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'UTC'"))
    local_times: Mapped[list[time]] = mapped_column(
        ARRAY(Time), nullable=False, server_default=text("ARRAY['09:00']::time[]")
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    __table_args__ = (
        CheckConstraint(
            "channel IN ('email', 'sms', 'push')", name="ck_reminder_preferences_channel"
        ),
        CheckConstraint("version > 0", name="ck_reminder_preferences_version"),
    )


class ReminderOccurrence(Base):
    __tablename__ = "reminder_occurrences"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    prescription_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("prescription_items.id", ondelete="CASCADE"), nullable=False
    )
    prescription_version: Mapped[int] = mapped_column(Integer, nullable=False)
    occurrence_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    dedupe_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'sent', 'cancelled', 'failed')",
            name="ck_reminder_occurrences_status",
        ),
        Index("ix_reminder_occurrences_due", "status", "occurrence_at"),
    )


class IntegrationOperation(Base, TimestampMixin):
    __tablename__ = "integration_operations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE")
    )
    outbox_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("outbox_events.id", ondelete="CASCADE"), nullable=False
    )
    channel: Mapped[str] = mapped_column(Text, nullable=False)
    state: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    last_attempt_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error_code: Mapped[str | None] = mapped_column(Text)
    provider_reference: Mapped[str | None] = mapped_column(Text)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    __table_args__ = (
        UniqueConstraint(
            "outbox_event_id", "channel", name="uq_integration_operations_event_channel"
        ),
        CheckConstraint(
            "state IN ('pending', 'succeeded', 'retrying', 'failed')",
            name="ck_integration_operations_state",
        ),
        CheckConstraint("version > 0", name="ck_integration_operations_version"),
        Index("ix_integration_operations_state", "channel", "state", "updated_at"),
    )


class AppointmentHistory(Base):
    __tablename__ = "appointment_history"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False
    )
    from_status: Mapped[str | None] = mapped_column(Text)
    to_status: Mapped[str] = mapped_column(Text, nullable=False)
    old_starts_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    old_ends_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    reason: Mapped[str | None] = mapped_column(Text)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (Index("ix_appointment_history_appointment", "appointment_id", "created_at"),)


class LeavePreview(Base):
    __tablename__ = "leave_previews"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expected_schedule_version: Mapped[int] = mapped_column(Integer, nullable=False)
    affected_hold_ids: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    affected_appointment_ids: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_by_actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="RESTRICT"), nullable=False
    )
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_leave_previews_interval"),
        CheckConstraint("expected_schedule_version > 0", name="ck_leave_previews_schedule_version"),
        Index("ix_leave_previews_doctor_expiry", "doctor_id", "expires_at"),
    )
