"""PostgreSQL booking foundation models.

The range columns are generated by PostgreSQL and are used by GiST exclusion
constraints.  Application checks improve error messages, while the database remains
the authority under concurrent writes.
"""

from __future__ import annotations

import uuid
from datetime import datetime, time
from typing import Any

from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Time,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSTZRANGE, UUID, ExcludeConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def uuid_default() -> uuid.UUID:
    return uuid.uuid4()


class Base(DeclarativeBase):
    """Declarative metadata root."""


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )


class Actor(Base, TimestampMixin):
    __tablename__ = "actors"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    subject_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))

    patient_profile: Mapped[PatientProfile | None] = relationship(back_populates="actor")
    doctor_profile: Mapped[Doctor | None] = relationship(back_populates="actor")

    __table_args__ = (
        CheckConstraint("role IN ('patient', 'doctor', 'admin')", name="ck_actors_role"),
    )


class PatientProfile(Base, TimestampMixin):
    __tablename__ = "patient_profiles"

    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="RESTRICT"), primary_key=True
    )
    display_name: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'Patient'")
    )

    actor: Mapped[Actor] = relationship(back_populates="patient_profile")
    holds: Mapped[list[SlotHold]] = relationship(back_populates="patient")
    appointments: Mapped[list[Appointment]] = relationship(back_populates="patient")


class Doctor(Base, TimestampMixin):
    __tablename__ = "doctors"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("actors.id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
    )
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    credentials: Mapped[str | None] = mapped_column(Text)
    specialization: Mapped[str | None] = mapped_column(Text)
    timezone: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'UTC'"))
    appointment_durations_minutes: Mapped[list[int]] = mapped_column(
        ARRAY(Integer), nullable=False, server_default=text("ARRAY[30]::integer[]")
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    schedule_version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    actor: Mapped[Actor] = relationship(back_populates="doctor_profile")
    working_hours: Mapped[list[DoctorWorkingHour]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan"
    )
    leave: Mapped[list[DoctorLeave]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan"
    )
    holds: Mapped[list[SlotHold]] = relationship(back_populates="doctor")
    appointments: Mapped[list[Appointment]] = relationship(back_populates="doctor")

    __table_args__ = (CheckConstraint("schedule_version > 0", name="ck_doctors_schedule_version"),)


class DoctorWorkingHour(Base, TimestampMixin):
    __tablename__ = "doctor_working_hours"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False
    )
    weekday: Mapped[int] = mapped_column(Integer, nullable=False)
    starts_local: Mapped[time] = mapped_column(Time, nullable=False)
    ends_local: Mapped[time] = mapped_column(Time, nullable=False)

    doctor: Mapped[Doctor] = relationship(back_populates="working_hours")

    __table_args__ = (
        CheckConstraint("weekday BETWEEN 0 AND 6", name="ck_working_hours_weekday"),
        CheckConstraint("starts_local < ends_local", name="ck_working_hours_interval"),
        UniqueConstraint(
            "doctor_id", "weekday", "starts_local", "ends_local", name="uq_working_hours_interval"
        ),
        Index("ix_working_hours_doctor_weekday", "doctor_id", "weekday"),
    )


class DoctorLeave(Base, TimestampMixin):
    __tablename__ = "doctor_leave"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reason: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))

    doctor: Mapped[Doctor] = relationship(back_populates="leave")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_doctor_leave_interval"),
        Index("ix_doctor_leave_doctor_interval", "doctor_id", "starts_at", "ends_at"),
    )


class SlotHold(Base, TimestampMixin):
    __tablename__ = "slot_holds"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.actor_id", ondelete="RESTRICT"),
        nullable=False,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    slot_range: Mapped[Any] = mapped_column(
        TSTZRANGE,
        Computed("tstzrange(starts_at, ends_at, '[)'::text)", persisted=True),
        nullable=False,
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'active'"))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    patient: Mapped[PatientProfile] = relationship(back_populates="holds")
    doctor: Mapped[Doctor] = relationship(back_populates="holds")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_slot_holds_interval"),
        CheckConstraint(
            "status IN ('active', 'released', 'expired', 'converted')", name="ck_slot_holds_status"
        ),
        ExcludeConstraint(
            ("doctor_id", "="),
            ("slot_range", "&&"),
            where=text("status = 'active'"),
            name="ex_slot_holds_active_overlap",
        ),
        Index("ix_slot_holds_patient_status", "patient_id", "status"),
        Index("ix_slot_holds_doctor_status_expiry", "doctor_id", "status", "expires_at"),
    )


class Appointment(Base, TimestampMixin):
    __tablename__ = "appointments"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.actor_id", ondelete="RESTRICT"),
        nullable=False,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False
    )
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    slot_range: Mapped[Any] = mapped_column(
        TSTZRANGE,
        Computed("tstzrange(starts_at, ends_at, '[)'::text)", persisted=True),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'confirmed'"))
    symptoms_text: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    patient: Mapped[PatientProfile] = relationship(back_populates="appointments")
    doctor: Mapped[Doctor] = relationship(back_populates="appointments")
    outbox_events: Mapped[list[OutboxEvent]] = relationship(back_populates="appointment")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="ck_appointments_interval"),
        CheckConstraint(
            "status IN ("
            "'confirmed', 'in_progress', 'completed', "
            "'cancelled_patient', 'cancelled_doctor', "
            "'cancelled_admin', 'cancelled_doctor_leave'"
            ")",
            name="ck_appointments_status",
        ),
        ExcludeConstraint(
            ("doctor_id", "="),
            ("slot_range", "&&"),
            where=text("status IN ('confirmed', 'in_progress')"),
            name="ex_appointments_active_overlap",
        ),
        Index("ix_appointments_patient_starts", "patient_id", "starts_at"),
        Index("ix_appointments_doctor_starts", "doctor_id", "starts_at"),
        Index("ix_appointments_status_starts", "status", "starts_at"),
    )


class IdempotencyRecord(Base):
    __tablename__ = "idempotency_records"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="RESTRICT"), nullable=False
    )
    method: Mapped[str] = mapped_column(String(8), nullable=False)
    route_template: Mapped[str] = mapped_column(Text, nullable=False)
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False)
    request_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    status_code: Mapped[int | None] = mapped_column(Integer)
    response_body: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint(
            "actor_id", "method", "route_template", "idempotency_key", name="uq_idempotency_scope"
        ),
        Index("ix_idempotency_created_at", "created_at"),
    )


class OutboxEvent(Base):
    __tablename__ = "outbox_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    aggregate_type: Mapped[str] = mapped_column(Text, nullable=False)
    aggregate_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("appointments.id", ondelete="CASCADE")
    )
    dedupe_key: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    next_attempt_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    last_error_code: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    appointment: Mapped[Appointment | None] = relationship(back_populates="outbox_events")

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'processing', 'succeeded', 'retrying', 'failed')",
            name="ck_outbox_status",
        ),
        UniqueConstraint(
            "event_type", "aggregate_type", "aggregate_id", "dedupe_key", name="uq_outbox_dedupe"
        ),
        Index("ix_outbox_appointment_id", "appointment_id"),
        Index("ix_outbox_claimable", "status", "next_attempt_at"),
    )


class AuditEvent(Base):
    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid_default
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("actors.id", ondelete="SET NULL")
    )
    action: Mapped[str] = mapped_column(Text, nullable=False)
    resource_type: Mapped[str] = mapped_column(Text, nullable=False)
    resource_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    request_id: Mapped[str | None] = mapped_column(Text)
    outcome: Mapped[str] = mapped_column(Text, nullable=False)
    reason: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("ix_audit_events_resource", "resource_type", "resource_id", "created_at"),
        Index("ix_audit_events_actor_created", "actor_id", "created_at"),
    )
